### ISSUE TITLE
Playbooks - Set params from a playbook pre-step

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1147]

**Comment by moshloop** [comment]
This is to populate param values / dropdown lists / schema  from  from an action

```yaml
- actions:
     - name: Lookup users from SQL
        sql: abc
     - name: Enter Username 
        params:
            - default: "{{ getLastAction().result}}
```
