### ISSUE TITLE
Error result missing in Sql action that returns recordset along with error

### ISSUE THREAD

**Issue by junaid-ebrahim** [flanksource/mission-control#1183]
When using the sql action with mssql ( but I suspect on all other sql types) , any raiserror message is missing in the result if the sql also returns a resultset, see example action below to reproduce, removing the `select 'test result';` fixes the issue

```
    - name: raiserror1
      if: "always()"
      sql:
        connection: connection://default/mssql-db
        driver: mssql
        query: >
          select 'test result';raiserror('test error message 1',11,0)
```
