### ISSUE TITLE
Playbook spec runs on are not used

### ISSUE THREAD

**Issue by adityathebe** [flanksource/mission-control#1428]
```yaml
spec:
  runsOn: ['aws']
  actions:
    - name: first
    - name: second
```

Even though the spec says the playbook should run on aws agent, it runs all the actions on the local agent because the actions do not have `runsOn = aws` on them.
