### ISSUE TITLE
Notification filter not working as expected

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#1450]
```
apiVersion: mission-control.flanksource.com/v1
kind: Notification
metadata:
  name: failing-kube-objects
  annotations:
      argocd.argoproj.io/sync-wave: "3"
spec:
  events:
    - config.unhealthy
    - config.warning
  to:
    connection: connection://mission-control/devops-infra-channel
  filter: (config.type == "Kubernetes::Deployment" || config.type == "Kubernetes::Pod") && jq('.metadata.ownerReferences[0].apiVersion', config.config) != "batch/v1"
```

Here when we remove the `jq('.metadata.ownerReferences[0].apiVersion', config.config) != "batch/v1"` , it works fine. We need a way to filter pods that are created by kube jobs and NOT send an alert for those
