### ISSUE TITLE
Alert sent even after `waitFor` added for statefulsets

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#1516]
![image (9)](https://github.com/user-attachments/assets/fa238ade-00d9-4c07-a1be-e824bd7c9a93)
![image (8)](https://github.com/user-attachments/assets/fd43e0c7-5fe7-4a54-a504-990f0e0408cb)
![image (10)](https://github.com/user-attachments/assets/a68c45ea-405c-4110-9e6a-855d5d435651)

```
apiVersion: mission-control.flanksource.com/v1
kind: Notification
metadata:
  name: failing-statefulset
  annotations:
      argocd.argoproj.io/sync-wave: "3"
spec:
  events:
    - config.unhealthy
    - config.warning
  to:
    connection: connection://mission-control/devops-infra-channel
  filter: config.type == "Kubernetes::StatefulSet"
  waitFor: 2m
 ```
