### ISSUE TITLE
Notifications - Inhibit Children

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1562]
When Inhibit children is checked, do not fire seperate notifications for direct children, rather include the name/status/reason of those children in the notification message

**Comment by moshloop** [comment]
```yaml
inhibit:
    - direction:  incoming/outgoing/all
       depth: 3
       types:
        - Component
        - Canary
        - Kubernetes::Pod
```
