### ISSUE TITLE
IFS slack notifications have error

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#1609]
https://app.flanksource.com/notifications/rules?id=4e8b2275-4055-425f-9f3b-39f4aa5966ee
Connection
```
apiVersion: mission-control.flanksource.com/v1
kind: Connection
metadata:
  name: dev-critical
  namespace: mission-control-agent
spec:
  slack:
    token:
      valueFrom:
        secretKeyRef:
          name: ifs-slack-token
          key: token
    channel: missioncontrol-critical-dev
    botName: Mission-Control-Agent
```

Notification spec
```
apiVersion: mission-control.flanksource.com/v1
kind: Notification
metadata:
  name: failing-helmrelease-beta
  namespace: default
spec:
  events:
    - config.unhealthy
    - config.warning
  to:
    connection: connection://ifs/dev-critical
  filter: config.type == "Kubernetes::HelmRelease" && config.tags.cluster == "ifs-beta-cluster"
  waitFor: 5m
```

Error 
`could not find secret ifs/slack-token: secrets "slack-token" not found`
