### ISSUE TITLE
Config health not updated quick enough. Sending out lot of false positives

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#1614]
Catalog changes show
![image](https://github.com/user-attachments/assets/32751057-06f9-43b8-bca1-51df5f814390)

Whereas in cluster 
```
status:                                                                               
  availableReplicas: 1                                                                
  conditions:                                                                         
  - lastTransitionTime: "2023-10-05T12:59:54Z"                                        
    lastUpdateTime: "2023-10-05T13:02:48Z"                                            
    message: ReplicaSet "external-secrets-cert-controller-6b57f97948" has successfully
      progressed.                                                                     
    reason: NewReplicaSetAvailable                                                    
    status: "True"                                                                    
    type: Progressing                                                                 
  - lastTransitionTime: "2024-11-12T14:06:38Z"                                        
    lastUpdateTime: "2024-11-12T14:06:38Z"                                            
    message: Deployment has minimum availability.                                     
    reason: MinimumReplicasAvailable                                                  
    status: "True"                                                                    
    type: Available                                                                   
```
