### ISSUE TITLE
Playbooks Actions - ForEach

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1627]
Run the action forEach catalog item e.g. 

```yaml
configs:
   - type: AWS::Zone
actions:
   - forEach:  {{ catalog_query('type: Kubernetes::Pod and zone: ' .config.name) }} 
```

- Get in-container process details for all pods in a deployment
- Terminate all pods in region
