### ISSUE TITLE
Playbooks - AI actions

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1642]
1. Generate a context for a config item:
* config
* changes
* analysis
* recent logs
* relatations

```yaml
actions:
  - ai:
      prompt: Using the context provided, as a Kubernetes engineeer find out why {.config.id} is not healthy, print the response using slack blocks api.
      groupNotifications: true
      config: '{{.id}}'
      changes:
        since: 2h
      analysis: 
        since: 2h
      logs:
        since: 2h
        playbook: kubernetes-logs
      relationships:
        - depth: 1
          changes:
            since: 2h
          analysis:
            since: 2h
          logs:
            since: 5h
            playbook: kubernetes-logs
  - notification:
      body: "{{ steps.ai.output }}"
```
