### ISSUE TITLE
AI Playbook - Draft Mode

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1710]
```
ai:
  draft: true
```

Just return the markdown that would be sent in the chat message

**Comment by adityathebe** [comment]
not sure I understand this. the markdown would also be saved in the `actions.result`?
![image](https://github.com/user-attachments/assets/fc8c987c-e8b5-45e2-bc0f-17fb68c38b52)

---
heres' the spec

```yaml
 actions:
  - name: diagnosis
    ai:
     ....
  - name: send notificaiton
    notification:
      title: Diagnosis report
      message: $(getLastAction.result.markdown)
      connection: connection://mc/flanksource-slack
```
