### ISSUE TITLE
AI Playbooks - Agents

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1719]
Allow defining a list of agents that can be called by specifying the playbooks e.g.

```
ai:
  - playbookAgents:
     - name: logs-*
     - name: trivy
```
