### ISSUE TITLE
Playbooks - Parameter lookup based on resource

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#1812]
```
parameters:
  - name: deployment
     type: config
     selector: 
       type: Kubernetes::Deployment
       search: namespace="{{.component.properties.namespace}}" cluster="{{.component.properties.cluster}} api"
actions:
  - connections:
        fromConfigItem: '{{params.deployment.id}}
```
