### ISSUE TITLE
AI playbook should use previous pod's logs for diagnosing a crashing pod

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/mission-control#1881]

**Comment by moshloop** [comment]
```yaml

ai:
   playbooks:
     - name: Logs
       if: status == "CrashLoopBackoff"
      params:
        config_id: $(.config.id)
        since: 24h
        json: true

```
