### ISSUE TITLE
Unable to clone gitlab repo in playbook

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#1966]
```
icon: kubernetes
title: Update EC2NodeClass in Prod
actions:
  - name: Create Pull Request With Changes
    gitops:
      pr:
        title: $(.params.commit_message)
      repo:
        url: $(.git.git.url | strings.ReplaceAll "ssh://git@" "https://")
        base: $(.git.git.branch)
        type: gitlab
        branch: edit-manifest-$(random.Alpha 8)
        password: {}
        username: {}
        connection: connection://ifs/gitlab
      commit:
        email: $(.user.email)
        author: $(.user.name)
        message: $(.params.commit_message)
      patches:
        - yq: >
            select(
              .kind=="$(.config.config | jq `.kind`)" and
              .metadata.name=="$(.config.config | jq `.metadata.name`)"
            ) .spec.amiSelectorTerms[].alias |= {{  index  (.params.source.config | jq ".status.amis[0].name"  | strings.Split "-" | reverse ) 0 }}
          path: $(.params.file)
configs:
  - agent: all
    types:
      - Kubernetes::EC2NodeClass
category: Kubernetes
parameters:
  - name: source
    type: config
    label: "Get AMI from:"
    properties:
      filter:
        - types:
            - Kubernetes::EC2NodeClass
  - name: commit_message
    label: Commit Message
    default: "chore: update $(.config.type)/$(.config.name)"
  - name: url
    label: Git Repo
    default: $(.git.git.url)
  - name: file
    label: File
    default: $(.git.git.file)
```

has errors in this playbook https://app.flanksource.com/playbooks/runs?playbook=01957e94-21d3-db5f-0dc1-f9788a96e5b8

whereas, this runs as expected with pretty much the same config https://app.flanksource.com/playbooks/runs?playbook=0194ca49-6a48-76ee-7664-033f39dec8ce
