### ISSUE TITLE
Log Action - Dedupe / Filter

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#2056]
```yaml

dedupe: 
  - message
filter:
  - !INFO*
mapping:
   message: 
       - log
       - message
       - msg
    timestamp:
       - @timestamp
       - created_at
    severity:
       - logLevel
       - severity
       - level
 ```
