### ISSUE TITLE
Last error message not cleared after canary passes

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control#2099]
```
status:
  checks:
    hello-world: 0195857d-357c-027e-4239-7e3a76ddb2c7
  status: Passed
  message: "hello world golang check: "
  replicas: 1
  errorMessage: 'Pod "hello-world-golang-1" is invalid:
    spec.tolerations[0].operator: Unsupported value: "Equals": supported values:
    "Equal", "Exists"'
```
when 
```
      resources:
        - kind: Pod
          spec:
            tolerations:
              - key: pool-type
                value: monitoring
                effect: NoSchedule
                operator: Equal
```

2nd example
```
status:
  checks:
    admin-api HTTP Internal: 01956b75-bb57-e149-5d72-4e2a437d7ae9
  status: Passed
  replicas: 1
  errorMessage: 'Get "https://<obfuscated>/docs/": dial tcp
    10.127.254.250:443: connect: connection refused'
```

when status is passed
