### ISSUE TITLE
Views - Replication

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#2163]

**Comment by adityathebe** [comment]
Agent:
  - agents list all their views, and push the tables for the views.
  - agents also sends the list of current active views so the upstream can delete it

Upstream:
  - when the upstream receives the table push, it renames the table by adding a suffix (agent id)
  - an viewRef should have agent_id:
    ```yaml
    viewRef:
      namespace: mc
      name: pipelines
      agent_id: f1a4da2a-cdd9-4c6e-adc0-438389c11fc9
    ```
