### ISSUE TITLE
Custom renders per component / property type 

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#235]
i.e. Using a https://github.com/jvatic/goja-babel provide an option to specify a JSX renderer content at a SystemTemplate level.

e.g. 

```yaml
components: []
renderers: 
    components:
        - name: abc
          type: EKSCluster
          jsx: "..."

     properties:
       - name: cpu
          jsx: "..."
```       

This would generate components with the name: `<System template name>-{component|property}-{name|kind}-name
