### ISSUE TITLE
Playbooks - take down actions

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#473]
e.g.
```yaml

action:
  - exec: kubectl create rbac abc
expiry: 8h
on:
   expiry:
      - exec: kubectl delete rbac
```
