### ISSUE TITLE
Connection permissions

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#638]
```
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-config-notifications-to-use-connection
spec:
  description: allow config notifications to use any connection
  subject:
    playbooks: *
    canary:
    scraper:
    topology:
    notification: config-notifications
  actions:
    - connection:use
  object:
	connections:
       - name: *
```
