### ISSUE TITLE
Playbook action - step filter

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#737]
e.g. used in conjunction with a delay to send a notification after 7 days, but don't send it the config is deleted (from config db or marked as deleted)

**Comment by adityathebe** [comment]
@moshloop If the filter fails we just skip that action and proceed with the rest of the action? Or should we have an option to 
- fail the entire run
- waitUntil

**Comment by moshloop** [comment]
Maybe we should follow the github actions model:

```yaml
if: always()
if: timeout()
if: fail()
if: success() 
if: skip() 
if: wait("2h") # bump run_action_start by this amount
```

Where these are functions that just returned a fixed value

So the filter can return multiple different values and based on that we perform necessary set
