### ISSUE TITLE
Action filter handle `timeout()`

### ISSUE THREAD

**Issue by adityathebe** [flanksource/mission-control#765]
```yaml
spec:
  actions:
    - name: Fetch all changes
      timeout: 1s
      sql:
        query: SELECT id FROM config_changes WHERE config_id = '{{.config.id}}'
        driver: postgres
        connection: connection://postgres/local
    - name: Send notification
      if: 'timeout()'
      exec:
        query: notify-send 'Previous action timed out'
```

In the above example, the filter `if: 'timeout()'`currently doesn't work because we do not save if an action failed due to timeout error. 

This might not be trivial as for eg in exec action, a timed out `cmd.Run()` doesn't tell that it failed due to context timeout.
