### ISSUE TITLE
Playbook: In gitops step, link of PR should in the first few lines

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/mission-control#872]

**Comment by moshloop** [comment]
This is probably something we want to return in the JSON e.g.
```yaml
stdout: abc
links:
  - name: "Github PR #1275"
     id: Github::PR/1275 # could be used in future to link the playbook back to the pr that is ingested
     url: https://github.com/...
     icon: pr
```
