### ISSUE TITLE
Playbook variables

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control#885]
```yaml
kind: Playbook
metadata:
  name: edit-kubernetes-manifests-gitops
spec:
  parameters:
  - default: "chore: update $(.config.type)/$(.config.name)"
    label: Commit Message
    name: commit_message
  - default: $(.config.config | neat | json | toYAML)
    label: ""
    name: yamlInput
    properties:
      size: large
    type: code

  configs:
    - labelSelector: 'kustomize.toolkit.fluxcd.io/name'

  env:
      - name: file_path
         template:  "$(.config.config | json | jq `.metadata.annotations["config.kubernetes.io/origin"]` | yaml | toJSON | json | jq `.path`"        
      - name: kustomization_path
         template:  {{ catalog_traverse .config.id  "Kubernetes::Kustomization").Config | json | jq `.spec.path` }}
      - name: git_branch
         template:  {{ catalog_traverse .config.id  "Kubernetes::Kustomization/Kubernetes::GitRepository").Config | json | jq `.spec.ref.branch`}}
  actions:
  
    - name: Create PR With Changes
      gitops:
        repo:
          url: $( .git_url | quote)
          connection: {{ .Values.playbooks.edit_kubernetes_manifests.git_connection }}
          base: $( .git_branch | quote)
          branch: edit-manifest-$(random.Alpha 8)
        commit:
          email: {{ .Values.playbooks.edit_kubernetes_manifests.git_commiter.email | quote }}
          author: {{ .Values.playbooks.edit_kubernetes_manifests.git_commiter.author | quote }}
          message: $(.params.commit_message | quote)
        pr:
          title: $(.params.commit_message | quote)
        patches:
          - path: '$(filepath.Join  .kustomization_path .file_path)'
            yq: |
              select(
                .kind=="$(.config.config | json | jq `.kind`)" and
                .metadata.name=="$(.config.config | json | jq `.metadata.name`)"
              ) |= $(.params.yamlInput)
{{ end }}
```
